### ISSUE TITLE
Does not run on Mojave

### ISSUE THREAD

**Issue by dazey77** [jnross/Bluetility#23]
![image](https://user-images.githubusercontent.com/76662697/199441767-392642c7-c598-4adc-a240-5e4bda35bf79.png)
I see only a window title bar with no clickable buttons.

**Comment by jnross** [comment]
I acknowledge this may be a real issue, but I don't plan to investigate or ever fix this.

**Comment by jnross** [comment]
I was wondering why you might be running such an old version of macOS, and I realize perhaps you might be on old hardware (though you didn't report anything about your hardware).  On some old hardware, CoreBluetooth doesn't work correctly, or at all.  It may have to do with the bluetooth hardware included, or the version of Bluetooth supported.  Take a look at this old issue: https://github.com/jnross/Bluetility/issues/10.  The conclusion was that this will not work on that old Mac Pro.  It's either a hardware or OS issue, not something that can be fixed in the application.

**Comment by jnross** [comment]
Also:  It is possible that I am wrong and that this can be fixed!  So although I don't plan to spend time on it, I'm quite willing to consider a PR if you can put changes together that get this working for you.  Good luck!

**Comment by dazey77** [comment]
Hi,
Thanks for getting back to me.  I run an older version as its less locked down and Mojave works very well.  I don’t really like the direction Apple have been taking OSX (or the hardware for that matter).   I run a 2012 quad core i7 Mac mini and a 2017 MacBook (the MacBook certainly supports BLE, not sure about the Mini).  I tested it on both with the same results so I guess its an OS issue.
Regards,
Jim

**Comment by jnross** [comment]
Old issue, closing.
