### ISSUE TITLE
Can't see MAC address

### ISSUE THREAD

**Issue by atrepca** [jnross/Bluetility#24]
Hi,

I just downloaded `version 1.4 (7)`, and I'm using it on a MacBook Pro M1 with macOS Monterey 12.6.1. The app doesn't show MAC addresses for any LE device, any idea why?

Thanks,

**Comment by jnross** [comment]
I do.  This is something that was possible in earlier versions of macOS via a workaround, akin to a private API.  Apple removed this in recent versions of macOS.  This information is long gone from the CoreBluetooth APIs, and the workaround is gone now too.  It's a shame for an engineering tool like this, but it was done for privacy reasons.

**Comment by jnross** [comment]
I guess one question I have for you is: why would you *expect* to see MAC addresses?  I don't believe this is mentioned in the README, the release notes, or the screenshots, is it?  I suppose it's mentioned in older release notes... maybe I should edit the more recent release notes to mention this was removed since it's no longer possible.

**Comment by atrepca** [comment]
Makes sense, Apple at it again :(

I saw the feature being added in [version 1.2](https://github.com/jnross/Bluetility/releases/tag/1.2), also [version 1.3](https://github.com/jnross/Bluetility/releases/tag/1.3) adding the copy MAC feature. No mention of this being dropped as a feature anywhere, hence my question.

Thanks for the quick reply!

**Comment by jnross** [comment]
Gotcha.  I added this to the release notes for 1.4: https://github.com/jnross/Bluetility/releases/tag/1.4
