### ISSUE TITLE
services are not populated

### ISSUE THREAD

**Issue by paulz** [jnross/Bluetility#27]
Thank you for making this app!

Seeing services in the tooltip, but they are not showing in the app main window, see screenshot:
<img width="816" alt="image" src="https://user-images.githubusercontent.com/59230/213888151-66059ce4-3ee5-4d6b-8acb-11003ff59c02.png">

But when I select iPhone or Apple Watch, I see list of services appearing after delay.

Logs window is also empty.

**Comment by paulz** [comment]
screenshot of the tooltip:
<img width="533" alt="image" src="https://user-images.githubusercontent.com/59230/213888205-0704a519-55b5-4de4-b986-808e0a00e796.png">

**Comment by jnross** [comment]
Hi @paulz:  Thanks for reporting your observations here.  Based on the behavior you described, it sounds like the Bluetility app might be working fine, but perhaps it is the KATALYST device that is behaving in an unexpected way.  You mention that when you connect to other devices the services are populated.  So that works.  But when you connect to the KATALYST device they aren't populated - the main difference here is that this is a different device which may behave differently.

Now let me address a couple of your points:
1. **The service UUIDs appear in the tooltip, but not the list:**  The tooltip shows data that appears in the device's **advertising** packet.  By spec and convention, the device should make available all the services mentioned in the advertising packet.  But there is nothing in the actual technology that forces this to be true.  It's totally possible for a device to advertise services it doesn't implement, and to implement services it doesn't advertise.
2. **The log window is empty:** You're right.  This feature is woefully under-implemented.  First, it only starts appending messages once opened, so if you want to see the messages you have to open this window before interacting.  Second, I only implemented log messages around characteristic interaction: reads, writes, and notifications.  I only built the features that were most useful to me.  If you'd like to see more log messages, pull requests welcome!

Note also that some Bluetooth devices will implement unusual or unintuitive behaviors to increase security or resist reverse engineering.  Perhaps that's what's going on here?

To conclude:  my best guess here is that Bluetility is behaving correctly but the KATALYST device is doing something unusual.  I can't be sure though.   I don't have a KATALYST device though, or another device that causes this misbehavior in Bluetility.  If you have more specific questions about the Bluetility code, I'll do what I can to help you make changes to further investigate this.

**Comment by jnross** [comment]
Old issue, no response.  Closing.
