### ISSUE TITLE
Request: View Mac Address

### ISSUE THREAD

**Issue by ncodee** [jnross/Bluetility#34]
Possible to add option to view mac addresses at a glance? 
Thanks

**Comment by jnross** [comment]
Hi @ncodee, 

I'm sorry, but this is not possible.  I wish it were!!  This is a very common request and I certainly agree it would be useful.  I'm afraid that Apple seems to have decided that revealing MAC addresses creates a privacy concern (even in engineering contexts) and doesn't make this information available.

You can see past requests for this here:
https://github.com/jnross/Bluetility/issues/4
https://github.com/jnross/Bluetility/issues/24

You can see my attempt to use a hacky workaround to implement this in cb21444243596f4dffa1409f8baa5fab8a140657, and then my removal of it after it stopped working since a macOS update:  ea374e8cfd760f1041259689bc70e5f43eec396f.

If you're aware of a new way I could implement this using CoreBluetooth, I would love to learn about it.  Even if it means submitting an exception request to Apple.  I'm convinced that the usefulness of this tool might help them see the value of this feature.

Yours,
Joe
