### ISSUE TITLE
No MAC addresses in tool tip

### ISSUE THREAD

**Issue by kylepyke** [jnross/Bluetility#35]
I have a bunch of devices showing up in the scanner, but not a single one produces a MAC address. It looks like this feature was released in v1.2, but not a single one of my devices shows a MAC address.

**Comment by jnross** [comment]
See also #4 #9 #24 #34.

**Comment by kylepyke** [comment]
Apologies! Thanks for the update. I should have searched prior issues, but the first result is the post indicating MAC addresses are shown in v1.2

Perhaps leave this issue open, so it's easier to find for others?

**Comment by jnross** [comment]
The viewing of MAC addresses was implemented in older versions based on a hacky workaround - this workaround was broken by changes in macOS Catalina or Big Sur, and formally removed in version [1.4](https://github.com/jnross/Bluetility/releases/tag/1.4) of Bluetility.  But even if you're running an older version than 1.4, the feature doesn't work because macOS doesn't allow this information to be accessed.
