### ISSUE TITLE
main window doesn't show any devices

### ISSUE THREAD

**Issue by kscheff** [jnross/Bluetility#6]
On my iMac (27-inch, Late 2013) running 10.14.6 (18G3020) there are no devices to see. The windows is not horizontally resizeable:

![image](https://user-images.githubusercontent.com/8903302/75460861-46670a80-5982-11ea-8d6d-b06b87c8bd4d.png)

Bluetility Version 1.1.1 (3) does show all devices:

![image](https://user-images.githubusercontent.com/8903302/75460815-351dfe00-5982-11ea-9167-37424453d83c.png)

**Comment by bdombro** [comment]
I have the same, no devices issue, for both 1.2 and 1.1.1 (3). On 10.14.6 b/c my company doesn't allow me to upgrade :-(

**Comment by jnross** [comment]
I took an old laptop and brought it back down to Mojave, and confirmed this issue.  It's pretty insidious, because if I build locally even with the latest Xcode, I don't have this problem.  It only occurs if I build on a Catalina machine and then transfer it over to the Mojave machine.  That makes it pretty tough to debug.  I'll keep at it though.  Pull requests welcome!

**Comment by bdombro** [comment]
Is with the release 1.2.1? I still see no devices :-( on Mojave

**Comment by jnross** [comment]
@bdombro:  It sounds like your issue might be different than the one originally reported here.  Consider filing this as a separate issue.  If you do, try to include as much detail as possible, including a screenshot.  Also, can you confirm whether any other apps that use bluetooth work on your computer?  Does this app work for you?  https://apps.apple.com/us/app/bluesee-ble-debugger/id1336679524?mt=12
