### ISSUE TITLE
howto find BLE mac address

### ISSUE THREAD

**Issue by pilot1981** [jnross/Bluetility#9]
Hi,
great app!

It's possible use it to find BLE mac address?

**Comment by jnross** [comment]
Hi @pilot1981, this was fixed in build 1.2 and later.  See the release notes here: https://github.com/jnross/Bluetility/releases/tag/1.2.  To see the MAC Address, make sure you have connected to the device at least once by clicking its cell in the leftmost column, and then hover your mouse over the device cell until the tooltip appears.
